---
# defaults file for kvm_provision
base_image_name: Fedora-Cloud-Base-34-1.2.x86_64.qcow2
base_image_url: https://download.fedoraproject.org/pub/fedora/linux/releases/34/Cloud/x86_64/images/{{ base_image_name }}
base_image_sha: b9b621b26725ba95442d9a56cbaa054784e0779a9522ec6eafff07c6e6f717ea
libvirt_pool_dir: "/var/lib/libvirt/images"
vm_name: f34-dev
vm_vcpus: 2
vm_ram_mb: 2048
vm_net: default
vm_root_pass: test123
cleanup_tmp: no
ssh_pub_key_libvirt_host_file: /tmp/id_rsa.pub
ssh_pub_key: ""

libvirt_host: localhost


# defaults file for domain_create

libvirt_connect: "qemu:///system"
libvirt_type: "kvm"
libvirt_temp_dir: "/var/tmp/libvirt"

# the prefix will be removed by the inventory plug-in to re-create the inventory hostname
# make sure that the name is fit as filename (without blanks)
virt_dom_name: "ansible_{{ inventory_hostname }}"
virt_dom_title: "Ansible created - {{ inventory_hostname_short }}"
virt_dom_description: "default domain description - replace me"

virt_dom_ram_mb: "1024"
virt_dom_vcpus: "2"
virt_dom_cpu_type: "host"

virt_dom_disk_size: "10"
virt_dom_disk_pool: "default"
virt_dom_disk_bus: "scsi"  # or virtio
virt_dom_disk_controller: "scsi,model=virtio-scsi"
virt_dom_disk_name: "sda"  # vda if virtio

virt_dom_network_name: "default"
virt_dom_network_hostif: "eth0"
virt_dom_network_model: "virtio"
virt_dom_network_type: "direct"
virt_dom_network_mac: "52:54:00:af:bb:59"
virt_dom_network_bootproto: "dhcp"

# Configure Static network
# virt_dom_network_bootproto: "static"
# virt_dom_network_static_options:
#   ip: "192.168.0.200"
#   netmask: "255.255.255.0"
#   gateway: "10.0.2.254"
#   nameserver: "10.0.2.1"

virt_dom_os_type: "Linux"
virt_dom_os_variant: "rhel7.9"
virt_dom_os_iso: "/var/lib/libvirt/images/rhel-server-7.9-x86_64-dvd.iso"
virt_dom_os_kickstart: "vm.ks" # .j2 will be used as template

virt_dom_os_hostname: "{{ inventory_hostname }}"

# default password for root and Ansible user
# the idea is to have a temporary password and use a follow-up
# playbook to set proper security (if at all required)
virt_dom_os_password: redhat
# you might create a crypted password with $ python -c 'import crypt; print(crypt.crypt("My Password"))'
virt_dom_os_password_crypted: false

# short name to uniquely identify LVM's system PV and VG
virt_dom_os_fs: rhel

# list of file systems:
virt_dom_os_file_systems:
  - mount: /
    type: xfs
    name: Root
    size: 5120
    label: ROOTFS
