---
- name: Check if base OS image is downloaded
  stat:
    path: "/tmp/{{ base_image_name }}"
  register: virt_image_state
  delegate_to: "{{ libvirt_host }}"

- name: Download base image
  when: not virt_image_state.stat.exists  
  get_url:
    url: "{{ base_image_url }}"
    dest: "/tmp/{{ base_image_name }}"
    checksum: "sha256:{{ base_image_sha }}"
  delegate_to: "{{ libvirt_host }}"

- name: Copy ssh pub key to libvirt host
  when: ssh_pub_key | length > 0
  copy:
    dest: "{{ ssh_pub_key_libvirt_host_file }}"
    content: "{{ ssh_pub_key }}"
    mode: 0400
  delegate_to: "{{ libvirt_host }}"

- name: Copy base image to libvirt directory
  copy:
    dest: "{{ libvirt_pool_dir }}/{{ vm_name }}.qcow2"
    src: "/tmp/{{ base_image_name }}"
    force: no
    remote_src: yes 
    mode: 0660
  register: copy_results
  delegate_to: "{{ libvirt_host }}"

- name: Configure the image
  when: copy_results is changed
  command: |
    virt-customize -a {{ libvirt_pool_dir }}/{{ vm_name }}.qcow2 \
    --hostname {{ vm_name }} \
    --root-password password:{{ vm_root_pass }} \
    --ssh-inject 'root:file:{{ ssh_pub_key_libvirt_host_file }}' \
    --uninstall cloud-init --selinux-relabel
  delegate_to: "{{ libvirt_host }}"
