---
- name: Enable IP Forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_file: "/etc/sysctl.d/{{ libvirt_setup_sysctl_ip_forward_filename }}"
    state: present

- name: install required packages to setup the libvirt host
  package:
    name: "{{ libvirt_host_packages }}"
    state: installed

- name: enable and start libvirtd service
  service:
    name: libvirtd
    enabled: true
    state: started

- name: Create and configure optional network
  when: libvirt_setup_network.name is defined
  block:
    - name: Define Bridge Network in Libvirt
      community.libvirt.virt_net:
        command: define
        name: "{{ libvirt_setup_network.name }}"
        xml: '{{ lookup("template", "network.xml.j2") }}'

    - name: Create Bridge Network in Libvirt
      community.libvirt.virt_net:
        command: create
        name: "{{ libvirt_setup_network.name }}"
        state: active

    - name: Bridge Network in Libvirt is set to Autostart
      community.libvirt.virt_net:
        name: "{{ libvirt_setup_network.name }}"
        autostart: true
