---
ansible-navigator:
  execution-environment:
    environment-variables:
      set:
        ANSIBLE_COLLECTIONS_PATHS: /home/jveverka/git/ansible
    volume-mounts:
      - dest: /home/jveverka/git/ansible
        options: z
        src: /home/jveverka/git/ansible
  logging:
    file: /tmp/log.txt
    level: critical
  playbook-artifact:
    enable: true
    replay: /tmp/ansible_homelab_artifact.json
    save-as: /tmp/ansible_homelab_artifact.json
