---
# Example of usage to create all the VMs in the inventory
# ansible-runner run -i inventory libvirt_domain_create.yml

- name: Create Example VM
  hosts: test_vms
  gather_facts: false
  become: true
  roles:
    - jwerak.libvirt_manage.libvirt_domain
