---
# example of usage to completely wipe out the domains and their attached storage
# ansible-playbook -i inventory libvirt_domain_remove.yml -K -l test[23].\* \
#   -e virt_dom_undefine=true -e virt_dom_remove_storage=true
- name: Remove all virtual machines
  hosts: all
  gather_facts: false
  become: true
  tags: virtual_machines
  tasks:
    - name: Include role to delete domain
      ansible.builtin.include_role:
        name: jwerak.libvirt_automated.libvirt_domain
        tasks_from: domain_destroy.yml
      vars:
        libvirt_domain_virt_dom_state: destroyed
        libvirt_domain_virt_dom_remove_storage: true
